# Site settings
title: ClutchWriter Designs
email: solutions@clutchwriter.com
description: Launch Your Brand With Custom Content, Design & Strategy
baseurl: "/clutchwriter"
url: https:/clutchwriter.com

# Build settings
markdown: kramdown


port: 8000

# > # this means to ignore newlines until "baseurl:"
